<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image:
            id: img
            size_hint_y: 8
        TextInput:
            id: user_query
            text: 'Enter Text'
            size_hint_y: 1
        Button:
            text: 'Search Image'
            size_hint_y: 1
            on_press: root.search_image()

<RootWidget>:
    FirstScreen:
        id: first_screen
        name: 'first_screen'